import { HijaiyahLetterGroupType } from "@/types/hijaiyah-type";

export const HijaiyahDatas: HijaiyahLetterGroupType[] = [
    {
        name: 'Alif',
        base: { arabic: 'ا', read: 'Alif' },
        a: { arabic: 'اَ', read: 'a' },
        i: { arabic: 'اِ', read: 'i' },
        u: { arabic: 'اُ', read: 'u' },
        aa: { arabic: 'اٰ', read: 'aa' },
        ii: { arabic: 'اَيْ', read: 'ii' },
        uu: { arabic: 'اُوْ', read: 'uu' },
        sukun: { arabic: '-', read: '-' },
        tasydid: { arabic: '-', read: '-' },
    },
    {
        name: 'Ba',
        base: { arabic: 'ب', read: 'Ba' },
        a: { arabic: 'بَ', read: 'ba' },
        i: { arabic: 'بِ', read: 'bi' },
        u: { arabic: 'بُ', read: 'bu' },
        aa: { arabic: 'بَا', read: 'baa' },
        ii: { arabic: 'بِيْ', read: 'bii' },
        uu: { arabic: 'بُوْ', read: 'buu' },
        sukun: { arabic: 'بَبْ', read: 'bab' },
        tasydid: { arabic: 'بَبَّ', read: 'babba' },
    },
    {
        name: 'Ta',
        base: { arabic: 'ت', read: 'Ta' },
        a: { arabic: 'تَ', read: 'ta' },
        i: { arabic: 'تِ', read: 'ti' },
        u: { arabic: 'تُ', read: 'tu' },
        aa: { arabic: 'تَا', read: 'taa' },
        ii: { arabic: 'تِيْ', read: 'tii' },
        uu: { arabic: 'تُوْ', read: 'tuu' },
        sukun: { arabic: 'بَتْ', read: 'bat' },
        tasydid: { arabic: 'بَتَّ', read: 'batta' },
    },
    {
        name: 'Tsa',
        base: { arabic: 'ث', read: 'Tsa' },
        a: { arabic: 'ثَ', read: 'tsa' },
        i: { arabic: 'ثِ', read: 'tsi' },
        u: { arabic: 'ثُ', read: 'tsu' },
        aa: { arabic: 'ثَا', read: 'tsaa' },
        ii: { arabic: 'ثِيْ', read: 'tsii' },
        uu: { arabic: 'ثُوْ', read: 'tsuu' },
        sukun: { arabic: 'بَثْ', read: 'bats' },
        tasydid: { arabic: 'بَثَّ', read: 'batssa' },
    },
    {
        name: 'Jim',
        base: { arabic: 'ج', read: 'Jim' },
        a: { arabic: 'جَ', read: 'ja' },
        i: { arabic: 'جِ', read: 'ji' },
        u: { arabic: 'جُ', read: 'ju' },
        aa: { arabic: 'جَا', read: 'jaa' },
        ii: { arabic: 'جِيْ', read: 'jii' },
        uu: { arabic: 'جُوْ', read: 'juu' },
        sukun: { arabic: 'بَجْ', read: 'baj' },
        tasydid: { arabic: 'بَجَّ', read: 'bajja' },
    },
    {
        name: 'Ha (Halq)',
        base: { arabic: 'ح', read: 'Ha' },
        a: { arabic: 'حَ', read: 'ha' },
        i: { arabic: 'حِ', read: 'hi' },
        u: { arabic: 'حُ', read: 'hu' },
        aa: { arabic: 'حَا', read: 'haa' },
        ii: { arabic: 'حِيْ', read: 'hii' },
        uu: { arabic: 'حُوْ', read: 'huu' },
        sukun: { arabic: 'بَحْ', read: 'bah' },
        tasydid: { arabic: 'بَحَّ', read: 'bahha' },
    },
    {
        name: 'Kho',
        base: { arabic: 'خ', read: 'Kho' },
        a: { arabic: 'خَ', read: 'kho' },
        i: { arabic: 'خِ', read: 'khoi' },
        u: { arabic: 'خُ', read: 'khu' },
        aa: { arabic: 'خَا', read: 'khoa' },
        ii: { arabic: 'خِيْ', read: 'khii' },
        uu: { arabic: 'خُوْ', read: 'khuu' },
        sukun: { arabic: 'بَخْ', read: 'bakh' },
        tasydid: { arabic: 'بَخَّ', read: 'bakhkho' },
    },
    {
        name: 'Dal',
        base: { arabic: 'د', read: 'Dal' },
        a: { arabic: 'دَ', read: 'da' },
        i: { arabic: 'دِ', read: 'di' },
        u: { arabic: 'دُ', read: 'du' },
        aa: { arabic: 'دَا', read: 'daa' },
        ii: { arabic: 'دِيْ', read: 'dii' },
        uu: { arabic: 'دُوْ', read: 'duu' },
        sukun: { arabic: 'بَدْ', read: 'bad' },
        tasydid: { arabic: 'بَدَّ', read: 'badda' },
    },
    {
        name: 'Dzal',
        base: { arabic: 'ذ', read: 'Dzal' },
        a: { arabic: 'ذَ', read: 'dza' },
        i: { arabic: 'ذِ', read: 'dzi' },
        u: { arabic: 'ذُ', read: 'dzu' },
        aa: { arabic: 'ذَا', read: 'dzaa' },
        ii: { arabic: 'ذِيْ', read: 'dzii' },
        uu: { arabic: 'ذُوْ', read: 'dzuu' },
        sukun: { arabic: 'بَذْ', read: 'badz' },
        tasydid: { arabic: 'بَذَّ', read: 'baddza' },
    },
    {
        name: 'Ro',
        base: { arabic: 'ر', read: 'Ro' },
        a: { arabic: 'رَ', read: 'ro' },
        i: { arabic: 'رِ', read: 'ri' },
        u: { arabic: 'رُ', read: 'ru' },
        aa: { arabic: 'رَا', read: 'roa' },
        ii: { arabic: 'رِيْ', read: 'rii' },
        uu: { arabic: 'رُوْ', read: 'ruu' },
        sukun: { arabic: 'بَرْ', read: 'bar' },
        tasydid: { arabic: 'بَرَّ', read: 'barro' },
    },
    {
        name: 'Zai',
        base: { arabic: 'ز', read: 'Zai' },
        a: { arabic: 'زَ', read: 'za' },
        i: { arabic: 'زِ', read: 'zi' },
        u: { arabic: 'زُ', read: 'zu' },
        aa: { arabic: 'زَا', read: 'zaa' },
        ii: { arabic: 'زِيْ', read: 'zii' },
        uu: { arabic: 'زُوْ', read: 'zuu' },
        sukun: { arabic: 'بَزْ', read: 'baz' },
        tasydid: { arabic: 'بَزَّ', read: 'bazza' },
    },
    {
        name: 'Sin',
        base: { arabic: 'س', read: 'Sin' },
        a: { arabic: 'سَ', read: 'sa' },
        i: { arabic: 'سِ', read: 'si' },
        u: { arabic: 'سُ', read: 'su' },
        aa: { arabic: 'سَا', read: 'saa' },
        ii: { arabic: 'سِيْ', read: 'sii' },
        uu: { arabic: 'سُوْ', read: 'suu' },
        sukun: { arabic: 'بَسْ', read: 'bas' },
        tasydid: { arabic: 'بَسَّ', read: 'bassa' },
    },
    {
        name: 'Syin',
        base: { arabic: 'ش', read: 'Syin' },
        a: { arabic: 'شَ', read: 'sya' },
        i: { arabic: 'شِ', read: 'syi' },
        u: { arabic: 'شُ', read: 'syu' },
        aa: { arabic: 'شَا', read: 'syaa' },
        ii: { arabic: 'شِيْ', read: 'syii' },
        uu: { arabic: 'شُوْ', read: 'syuu' },
        sukun: { arabic: 'بَشْ', read: 'basy' },
        tasydid: { arabic: 'بَشَّ', read: 'basysya' },
    },
    {
        name: 'Shod',
        base: { arabic: 'ص', read: 'Shod' },
        a: { arabic: 'صَ', read: 'sho' },
        i: { arabic: 'صِ', read: 'shoi' },
        u: { arabic: 'صُ', read: 'shu' },
        aa: { arabic: 'صَا', read: 'shoa' },
        ii: { arabic: 'صِيْ', read: 'shii' },
        uu: { arabic: 'صُوْ', read: 'shuu' },
        sukun: { arabic: 'بَصْ', read: 'bash' },
        tasydid: { arabic: 'بَصَّ', read: 'bashsho' },
    },
    {
        name: 'Dhod',
        base: { arabic: 'ض', read: 'Dhod' },
        a: { arabic: 'ضَ', read: 'dho' },
        i: { arabic: 'ضِ', read: 'dhoi' },
        u: { arabic: 'ضُ', read: 'dhu' },
        aa: { arabic: 'ضَا', read: 'dhoa' },
        ii: { arabic: 'ضِيْ', read: 'dhii' },
        uu: { arabic: 'ضُوْ', read: 'dhuu' },
        sukun: { arabic: 'بَضْ', read: 'badh' },
        tasydid: { arabic: 'بَضَّ', read: 'badhdho' },
    },
    {
        name: 'Tho',
        base: { arabic: 'ط', read: 'Tho' },
        a: { arabic: 'طَ', read: 'tho' },
        i: { arabic: 'طِ', read: 'thoi' },
        u: { arabic: 'طُ', read: 'thu' },
        aa: { arabic: 'طَا', read: 'thoa' },
        ii: { arabic: 'طِيْ', read: 'thii' },
        uu: { arabic: 'طُوْ', read: 'thuu' },
        sukun: { arabic: 'بَطْ', read: 'bat' },
        tasydid: { arabic: 'بَطَّ', read: 'battho' },
    },
    {
        name: 'Zho',
        base: { arabic: 'ظ', read: 'Zho' },
        a: { arabic: 'ظَ', read: 'zho' },
        i: { arabic: 'ظِ', read: 'zhoi' },
        u: { arabic: 'ظُ', read: 'zhu' },
        aa: { arabic: 'ظَا', read: 'zhoa' },
        ii: { arabic: 'ظِيْ', read: 'zhii' },
        uu: { arabic: 'ظُوْ', read: 'zhuu' },
        sukun: { arabic: 'بَظْ', read: 'bazh' },
        tasydid: { arabic: 'بَظَّ', read: 'bazhzho' },
    },
    {
        name: 'Ain',
        base: { arabic: 'ع', read: 'Ain' },
        a: { arabic: 'عَ', read: 'a\'' },
        i: { arabic: 'عِ', read: 'i\'' },
        u: { arabic: 'عُ', read: 'u\'' },
        aa: { arabic: 'عَا', read: 'aa\'' },
        ii: { arabic: 'عِيْ', read: 'ii\'' },
        uu: { arabic: 'عُوْ', read: 'uu\'' },
        sukun: { arabic: 'بَعْ', read: 'ba\'' },
        tasydid: { arabic: 'بَعَّ', read: 'ba\'\'a' },
    },
    {
        name: 'Ghoin',
        base: { arabic: 'غ', read: 'Ghoin' },
        a: { arabic: 'غَ', read: 'gho' },
        i: { arabic: 'غِ', read: 'ghoi' },
        u: { arabic: 'غُ', read: 'ghu' },
        aa: { arabic: 'غَا', read: 'ghoa' },
        ii: { arabic: 'غِيْ', read: 'ghii' },
        uu: { arabic: 'غُوْ', read: 'ghuu' },
        sukun: { arabic: 'بَغْ', read: 'bagh' },
        tasydid: { arabic: 'بَغَّ', read: 'baghgho' },
    },
    {
        name: 'Fa',
        base: { arabic: 'ف', read: 'Fa' },
        a: { arabic: 'فَ', read: 'fa' },
        i: { arabic: 'فِ', read: 'fi' },
        u: { arabic: 'فُ', read: 'fu' },
        aa: { arabic: 'فَا', read: 'faa' },
        ii: { arabic: 'فِيْ', read: 'fii' },
        uu: { arabic: 'فُوْ', read: 'fuu' },
        sukun: { arabic: 'بَفْ', read: 'baf' },
        tasydid: { arabic: 'بَفَّ', read: 'baffa' },
    },
    {
        name: 'Qof',
        base: { arabic: 'ق', read: 'Qof' },
        a: { arabic: 'قَ', read: 'qo' },
        i: { arabic: 'قِ', read: 'qoi' },
        u: { arabic: 'قُ', read: 'qu' },
        aa: { arabic: 'قَا', read: 'qoa' },
        ii: { arabic: 'قِيْ', read: 'qii' },
        uu: { arabic: 'قُوْ', read: 'quu' },
        sukun: { arabic: 'بَقْ', read: 'baq' },
        tasydid: { arabic: 'بَقَّ', read: 'baqqo' },
    },
    {
        name: 'Kaf',
        base: { arabic: 'ك', read: 'Kaf' },
        a: { arabic: 'كَ', read: 'ka' },
        i: { arabic: 'كِ', read: 'ki' },
        u: { arabic: 'كُ', read: 'ku' },
        aa: { arabic: 'كَا', read: 'kaa' },
        ii: { arabic: 'كِيْ', read: 'kii' },
        uu: { arabic: 'كُوْ', read: 'kuu' },
        sukun: { arabic: 'بَكْ', read: 'bak' },
        tasydid: { arabic: 'بَكَّ', read: 'bakka' },
    },
    {
        name: 'Lam',
        base: { arabic: 'ل', read: 'Lam' },
        a: { arabic: 'لَ', read: 'la' },
        i: { arabic: 'لِ', read: 'li' },
        u: { arabic: 'لُ', read: 'lu' },
        aa: { arabic: 'لَا', read: 'laa' },
        ii: { arabic: 'لِيْ', read: 'lii' },
        uu: { arabic: 'لُوْ', read: 'luu' },
        sukun: { arabic: 'بَلْ', read: 'bal' },
        tasydid: { arabic: 'بَلَّ', read: 'balla' },
    },
    {
        name: 'Mim',
        base: { arabic: 'م', read: 'Mim' },
        a: { arabic: 'مَ', read: 'ma' },
        i: { arabic: 'مِ', read: 'mi' },
        u: { arabic: 'مُ', read: 'mu' },
        aa: { arabic: 'مَا', read: 'maa' },
        ii: { arabic: 'مِيْ', read: 'mii' },
        uu: { arabic: 'مُوْ', read: 'muu' },
        sukun: { arabic: 'بَمْ', read: 'bam' },
        tasydid: { arabic: 'بَمَّ', read: 'bamma' },
    },
    {
        name: 'Nun',
        base: { arabic: 'ن', read: 'Nun' },
        a: { arabic: 'نَ', read: 'na' },
        i: { arabic: 'نِ', read: 'ni' },
        u: { arabic: 'نُ', read: 'nu' },
        aa: { arabic: 'نَا', read: 'naa' },
        ii: { arabic: 'نِيْ', read: 'nii' },
        uu: { arabic: 'نُوْ', read: 'nuu' },
        sukun: { arabic: 'بَنْ', read: 'ban' },
        tasydid: { arabic: 'بَنَّ', read: 'banna' },
    },
    {
        name: 'Wawu',
        base: { arabic: 'و', read: 'Wawu' },
        a: { arabic: 'وَ', read: 'wa' },
        i: { arabic: 'وِ', read: 'wi' },
        u: { arabic: 'وُ', read: 'wu' },
        aa: { arabic: 'وَا', read: 'waa' },
        ii: { arabic: 'وِيْ', read: 'wii' },
        uu: { arabic: 'وُوْ', read: 'wuu' },
        sukun: { arabic: 'بَوْ', read: 'bau' },
        tasydid: { arabic: 'بَوَّ', read: 'bawwa' },
    },
    {
        name: 'Ha',
        base: { arabic: 'هـ', read: 'Ha' },
        a: { arabic: 'هَ', read: 'ha' },
        i: { arabic: 'هِ', read: 'hi' },
        u: { arabic: 'هُ', read: 'hu' },
        aa: { arabic: 'هَا', read: 'haa' },
        ii: { arabic: 'هِيْ', read: 'hii' },
        uu: { arabic: 'هُوْ', read: 'huu' },
        sukun: { arabic: 'بَهْ', read: 'bah' },
        tasydid: { arabic: 'بَهَّ', read: 'bahha' },
    },
    {
        name: 'Ya',
        base: { arabic: 'ي', read: 'Ya' },
        a: { arabic: 'يَ', read: 'ya' },
        i: { arabic: 'يِ', read: 'yi' },
        u: { arabic: 'يُ', read: 'yu' },
        aa: { arabic: 'يَا', read: 'yaa' },
        ii: { arabic: 'يِيْ', read: 'yii' },
        uu: { arabic: 'يُوْ', read: 'yuu' },
        sukun: { arabic: 'بَيْ', read: 'bai' },
        tasydid: { arabic: 'بَيَّ', read: 'bayya' },
    },
]