/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiswaIndexRouteImport } from './routes/siswa/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as SiswaMenulisHijaiyahIndexRouteImport } from './routes/siswa/menulis-hijaiyah/index'
import { Route as SiswaIqraIndexRouteImport } from './routes/siswa/iqra/index'
import { Route as SiswaAyatPendekIndexRouteImport } from './routes/siswa/ayat-pendek/index'
import { Route as SiswaIqraTanwinIndexRouteImport } from './routes/siswa/iqra/tanwin/index'
import { Route as SiswaIqraSukunTasydidIndexRouteImport } from './routes/siswa/iqra/sukun-tasydid/index'
import { Route as SiswaIqraSambungHurufIndexRouteImport } from './routes/siswa/iqra/sambung-huruf/index'
import { Route as SiswaIqraMadIndexRouteImport } from './routes/siswa/iqra/mad/index'
import { Route as SiswaIqraHijaiyahIndexRouteImport } from './routes/siswa/iqra/hijaiyah/index'
import { Route as SiswaIqraHarakatIndexRouteImport } from './routes/siswa/iqra/harakat/index'
import { Route as SiswaAyatPendekSurahIndexRouteImport } from './routes/siswa/ayat-pendek/$surah/index'
import { Route as SiswaIqraHijaiyahLetterRouteImport } from './routes/siswa/iqra/hijaiyah/$letter'
import { Route as SiswaAyatPendekIsyaratSurahIndexRouteImport } from './routes/siswa/ayat-pendek/isyarat/$surah/index'
import { Route as SiswaIqraHijaiyahIsyaratLetterRouteImport } from './routes/siswa/iqra/hijaiyah/isyarat/$letter'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIndexRoute = SiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const SiswaMenulisHijaiyahIndexRoute =
  SiswaMenulisHijaiyahIndexRouteImport.update({
    id: '/siswa/menulis-hijaiyah/',
    path: '/siswa/menulis-hijaiyah/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiswaIqraIndexRoute = SiswaIqraIndexRouteImport.update({
  id: '/siswa/iqra/',
  path: '/siswa/iqra/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaAyatPendekIndexRoute = SiswaAyatPendekIndexRouteImport.update({
  id: '/siswa/ayat-pendek/',
  path: '/siswa/ayat-pendek/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIqraTanwinIndexRoute = SiswaIqraTanwinIndexRouteImport.update({
  id: '/siswa/iqra/tanwin/',
  path: '/siswa/iqra/tanwin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIqraSukunTasydidIndexRoute =
  SiswaIqraSukunTasydidIndexRouteImport.update({
    id: '/siswa/iqra/sukun-tasydid/',
    path: '/siswa/iqra/sukun-tasydid/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiswaIqraSambungHurufIndexRoute =
  SiswaIqraSambungHurufIndexRouteImport.update({
    id: '/siswa/iqra/sambung-huruf/',
    path: '/siswa/iqra/sambung-huruf/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiswaIqraMadIndexRoute = SiswaIqraMadIndexRouteImport.update({
  id: '/siswa/iqra/mad/',
  path: '/siswa/iqra/mad/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIqraHijaiyahIndexRoute = SiswaIqraHijaiyahIndexRouteImport.update({
  id: '/siswa/iqra/hijaiyah/',
  path: '/siswa/iqra/hijaiyah/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaIqraHarakatIndexRoute = SiswaIqraHarakatIndexRouteImport.update({
  id: '/siswa/iqra/harakat/',
  path: '/siswa/iqra/harakat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaAyatPendekSurahIndexRoute =
  SiswaAyatPendekSurahIndexRouteImport.update({
    id: '/siswa/ayat-pendek/$surah/',
    path: '/siswa/ayat-pendek/$surah/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiswaIqraHijaiyahLetterRoute = SiswaIqraHijaiyahLetterRouteImport.update({
  id: '/siswa/iqra/hijaiyah/$letter',
  path: '/siswa/iqra/hijaiyah/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaAyatPendekIsyaratSurahIndexRoute =
  SiswaAyatPendekIsyaratSurahIndexRouteImport.update({
    id: '/siswa/ayat-pendek/isyarat/$surah/',
    path: '/siswa/ayat-pendek/isyarat/$surah/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiswaIqraHijaiyahIsyaratLetterRoute =
  SiswaIqraHijaiyahIsyaratLetterRouteImport.update({
    id: '/siswa/iqra/hijaiyah/isyarat/$letter',
    path: '/siswa/iqra/hijaiyah/isyarat/$letter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/siswa/': typeof SiswaIndexRoute
  '/siswa/ayat-pendek/': typeof SiswaAyatPendekIndexRoute
  '/siswa/iqra/': typeof SiswaIqraIndexRoute
  '/siswa/menulis-hijaiyah/': typeof SiswaMenulisHijaiyahIndexRoute
  '/siswa/iqra/hijaiyah/$letter': typeof SiswaIqraHijaiyahLetterRoute
  '/siswa/ayat-pendek/$surah/': typeof SiswaAyatPendekSurahIndexRoute
  '/siswa/iqra/harakat/': typeof SiswaIqraHarakatIndexRoute
  '/siswa/iqra/hijaiyah/': typeof SiswaIqraHijaiyahIndexRoute
  '/siswa/iqra/mad/': typeof SiswaIqraMadIndexRoute
  '/siswa/iqra/sambung-huruf/': typeof SiswaIqraSambungHurufIndexRoute
  '/siswa/iqra/sukun-tasydid/': typeof SiswaIqraSukunTasydidIndexRoute
  '/siswa/iqra/tanwin/': typeof SiswaIqraTanwinIndexRoute
  '/siswa/iqra/hijaiyah/isyarat/$letter': typeof SiswaIqraHijaiyahIsyaratLetterRoute
  '/siswa/ayat-pendek/isyarat/$surah/': typeof SiswaAyatPendekIsyaratSurahIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/siswa': typeof SiswaIndexRoute
  '/siswa/ayat-pendek': typeof SiswaAyatPendekIndexRoute
  '/siswa/iqra': typeof SiswaIqraIndexRoute
  '/siswa/menulis-hijaiyah': typeof SiswaMenulisHijaiyahIndexRoute
  '/siswa/iqra/hijaiyah/$letter': typeof SiswaIqraHijaiyahLetterRoute
  '/siswa/ayat-pendek/$surah': typeof SiswaAyatPendekSurahIndexRoute
  '/siswa/iqra/harakat': typeof SiswaIqraHarakatIndexRoute
  '/siswa/iqra/hijaiyah': typeof SiswaIqraHijaiyahIndexRoute
  '/siswa/iqra/mad': typeof SiswaIqraMadIndexRoute
  '/siswa/iqra/sambung-huruf': typeof SiswaIqraSambungHurufIndexRoute
  '/siswa/iqra/sukun-tasydid': typeof SiswaIqraSukunTasydidIndexRoute
  '/siswa/iqra/tanwin': typeof SiswaIqraTanwinIndexRoute
  '/siswa/iqra/hijaiyah/isyarat/$letter': typeof SiswaIqraHijaiyahIsyaratLetterRoute
  '/siswa/ayat-pendek/isyarat/$surah': typeof SiswaAyatPendekIsyaratSurahIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/siswa/': typeof SiswaIndexRoute
  '/siswa/ayat-pendek/': typeof SiswaAyatPendekIndexRoute
  '/siswa/iqra/': typeof SiswaIqraIndexRoute
  '/siswa/menulis-hijaiyah/': typeof SiswaMenulisHijaiyahIndexRoute
  '/siswa/iqra/hijaiyah/$letter': typeof SiswaIqraHijaiyahLetterRoute
  '/siswa/ayat-pendek/$surah/': typeof SiswaAyatPendekSurahIndexRoute
  '/siswa/iqra/harakat/': typeof SiswaIqraHarakatIndexRoute
  '/siswa/iqra/hijaiyah/': typeof SiswaIqraHijaiyahIndexRoute
  '/siswa/iqra/mad/': typeof SiswaIqraMadIndexRoute
  '/siswa/iqra/sambung-huruf/': typeof SiswaIqraSambungHurufIndexRoute
  '/siswa/iqra/sukun-tasydid/': typeof SiswaIqraSukunTasydidIndexRoute
  '/siswa/iqra/tanwin/': typeof SiswaIqraTanwinIndexRoute
  '/siswa/iqra/hijaiyah/isyarat/$letter': typeof SiswaIqraHijaiyahIsyaratLetterRoute
  '/siswa/ayat-pendek/isyarat/$surah/': typeof SiswaAyatPendekIsyaratSurahIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/siswa/'
    | '/siswa/ayat-pendek/'
    | '/siswa/iqra/'
    | '/siswa/menulis-hijaiyah/'
    | '/siswa/iqra/hijaiyah/$letter'
    | '/siswa/ayat-pendek/$surah/'
    | '/siswa/iqra/harakat/'
    | '/siswa/iqra/hijaiyah/'
    | '/siswa/iqra/mad/'
    | '/siswa/iqra/sambung-huruf/'
    | '/siswa/iqra/sukun-tasydid/'
    | '/siswa/iqra/tanwin/'
    | '/siswa/iqra/hijaiyah/isyarat/$letter'
    | '/siswa/ayat-pendek/isyarat/$surah/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/siswa'
    | '/siswa/ayat-pendek'
    | '/siswa/iqra'
    | '/siswa/menulis-hijaiyah'
    | '/siswa/iqra/hijaiyah/$letter'
    | '/siswa/ayat-pendek/$surah'
    | '/siswa/iqra/harakat'
    | '/siswa/iqra/hijaiyah'
    | '/siswa/iqra/mad'
    | '/siswa/iqra/sambung-huruf'
    | '/siswa/iqra/sukun-tasydid'
    | '/siswa/iqra/tanwin'
    | '/siswa/iqra/hijaiyah/isyarat/$letter'
    | '/siswa/ayat-pendek/isyarat/$surah'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/register'
    | '/siswa/'
    | '/siswa/ayat-pendek/'
    | '/siswa/iqra/'
    | '/siswa/menulis-hijaiyah/'
    | '/siswa/iqra/hijaiyah/$letter'
    | '/siswa/ayat-pendek/$surah/'
    | '/siswa/iqra/harakat/'
    | '/siswa/iqra/hijaiyah/'
    | '/siswa/iqra/mad/'
    | '/siswa/iqra/sambung-huruf/'
    | '/siswa/iqra/sukun-tasydid/'
    | '/siswa/iqra/tanwin/'
    | '/siswa/iqra/hijaiyah/isyarat/$letter'
    | '/siswa/ayat-pendek/isyarat/$surah/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SiswaIndexRoute: typeof SiswaIndexRoute
  SiswaAyatPendekIndexRoute: typeof SiswaAyatPendekIndexRoute
  SiswaIqraIndexRoute: typeof SiswaIqraIndexRoute
  SiswaMenulisHijaiyahIndexRoute: typeof SiswaMenulisHijaiyahIndexRoute
  SiswaIqraHijaiyahLetterRoute: typeof SiswaIqraHijaiyahLetterRoute
  SiswaAyatPendekSurahIndexRoute: typeof SiswaAyatPendekSurahIndexRoute
  SiswaIqraHarakatIndexRoute: typeof SiswaIqraHarakatIndexRoute
  SiswaIqraHijaiyahIndexRoute: typeof SiswaIqraHijaiyahIndexRoute
  SiswaIqraMadIndexRoute: typeof SiswaIqraMadIndexRoute
  SiswaIqraSambungHurufIndexRoute: typeof SiswaIqraSambungHurufIndexRoute
  SiswaIqraSukunTasydidIndexRoute: typeof SiswaIqraSukunTasydidIndexRoute
  SiswaIqraTanwinIndexRoute: typeof SiswaIqraTanwinIndexRoute
  SiswaIqraHijaiyahIsyaratLetterRoute: typeof SiswaIqraHijaiyahIsyaratLetterRoute
  SiswaAyatPendekIsyaratSurahIndexRoute: typeof SiswaAyatPendekIsyaratSurahIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/': {
      id: '/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof SiswaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/siswa/menulis-hijaiyah/': {
      id: '/siswa/menulis-hijaiyah/'
      path: '/siswa/menulis-hijaiyah'
      fullPath: '/siswa/menulis-hijaiyah/'
      preLoaderRoute: typeof SiswaMenulisHijaiyahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/': {
      id: '/siswa/iqra/'
      path: '/siswa/iqra'
      fullPath: '/siswa/iqra/'
      preLoaderRoute: typeof SiswaIqraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/ayat-pendek/': {
      id: '/siswa/ayat-pendek/'
      path: '/siswa/ayat-pendek'
      fullPath: '/siswa/ayat-pendek/'
      preLoaderRoute: typeof SiswaAyatPendekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/tanwin/': {
      id: '/siswa/iqra/tanwin/'
      path: '/siswa/iqra/tanwin'
      fullPath: '/siswa/iqra/tanwin/'
      preLoaderRoute: typeof SiswaIqraTanwinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/sukun-tasydid/': {
      id: '/siswa/iqra/sukun-tasydid/'
      path: '/siswa/iqra/sukun-tasydid'
      fullPath: '/siswa/iqra/sukun-tasydid/'
      preLoaderRoute: typeof SiswaIqraSukunTasydidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/sambung-huruf/': {
      id: '/siswa/iqra/sambung-huruf/'
      path: '/siswa/iqra/sambung-huruf'
      fullPath: '/siswa/iqra/sambung-huruf/'
      preLoaderRoute: typeof SiswaIqraSambungHurufIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/mad/': {
      id: '/siswa/iqra/mad/'
      path: '/siswa/iqra/mad'
      fullPath: '/siswa/iqra/mad/'
      preLoaderRoute: typeof SiswaIqraMadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/hijaiyah/': {
      id: '/siswa/iqra/hijaiyah/'
      path: '/siswa/iqra/hijaiyah'
      fullPath: '/siswa/iqra/hijaiyah/'
      preLoaderRoute: typeof SiswaIqraHijaiyahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/harakat/': {
      id: '/siswa/iqra/harakat/'
      path: '/siswa/iqra/harakat'
      fullPath: '/siswa/iqra/harakat/'
      preLoaderRoute: typeof SiswaIqraHarakatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/ayat-pendek/$surah/': {
      id: '/siswa/ayat-pendek/$surah/'
      path: '/siswa/ayat-pendek/$surah'
      fullPath: '/siswa/ayat-pendek/$surah/'
      preLoaderRoute: typeof SiswaAyatPendekSurahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/hijaiyah/$letter': {
      id: '/siswa/iqra/hijaiyah/$letter'
      path: '/siswa/iqra/hijaiyah/$letter'
      fullPath: '/siswa/iqra/hijaiyah/$letter'
      preLoaderRoute: typeof SiswaIqraHijaiyahLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/ayat-pendek/isyarat/$surah/': {
      id: '/siswa/ayat-pendek/isyarat/$surah/'
      path: '/siswa/ayat-pendek/isyarat/$surah'
      fullPath: '/siswa/ayat-pendek/isyarat/$surah/'
      preLoaderRoute: typeof SiswaAyatPendekIsyaratSurahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa/iqra/hijaiyah/isyarat/$letter': {
      id: '/siswa/iqra/hijaiyah/isyarat/$letter'
      path: '/siswa/iqra/hijaiyah/isyarat/$letter'
      fullPath: '/siswa/iqra/hijaiyah/isyarat/$letter'
      preLoaderRoute: typeof SiswaIqraHijaiyahIsyaratLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SiswaIndexRoute: SiswaIndexRoute,
  SiswaAyatPendekIndexRoute: SiswaAyatPendekIndexRoute,
  SiswaIqraIndexRoute: SiswaIqraIndexRoute,
  SiswaMenulisHijaiyahIndexRoute: SiswaMenulisHijaiyahIndexRoute,
  SiswaIqraHijaiyahLetterRoute: SiswaIqraHijaiyahLetterRoute,
  SiswaAyatPendekSurahIndexRoute: SiswaAyatPendekSurahIndexRoute,
  SiswaIqraHarakatIndexRoute: SiswaIqraHarakatIndexRoute,
  SiswaIqraHijaiyahIndexRoute: SiswaIqraHijaiyahIndexRoute,
  SiswaIqraMadIndexRoute: SiswaIqraMadIndexRoute,
  SiswaIqraSambungHurufIndexRoute: SiswaIqraSambungHurufIndexRoute,
  SiswaIqraSukunTasydidIndexRoute: SiswaIqraSukunTasydidIndexRoute,
  SiswaIqraTanwinIndexRoute: SiswaIqraTanwinIndexRoute,
  SiswaIqraHijaiyahIsyaratLetterRoute: SiswaIqraHijaiyahIsyaratLetterRoute,
  SiswaAyatPendekIsyaratSurahIndexRoute: SiswaAyatPendekIsyaratSurahIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
