/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as MenulisHijaiyahRouteImport } from './routes/menulis-hijaiyah'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IqraIndexRouteImport } from './routes/iqra/index'
import { Route as AyatPendekIndexRouteImport } from './routes/ayat-pendek/index'
import { Route as IqraTanwinRouteImport } from './routes/iqra/tanwin'
import { Route as IqraSukunTasydidRouteImport } from './routes/iqra/sukun-tasydid'
import { Route as IqraSambungHurufRouteImport } from './routes/iqra/sambung-huruf'
import { Route as IqraMadRouteImport } from './routes/iqra/mad'
import { Route as IqraHarakatRouteImport } from './routes/iqra/harakat'
import { Route as AyatPendekSurahRouteImport } from './routes/ayat-pendek/$surah'
import { Route as IqraHijaiyahIndexRouteImport } from './routes/iqra/hijaiyah/index'
import { Route as IqraHijaiyahLetterRouteImport } from './routes/iqra/hijaiyah/$letter'
import { Route as AyatPendekIsyaratSurahRouteImport } from './routes/ayat-pendek/isyarat/$surah'
import { Route as IqraHijaiyahIsyaratLetterRouteImport } from './routes/iqra/hijaiyah/isyarat/$letter'

const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const MenulisHijaiyahRoute = MenulisHijaiyahRouteImport.update({
  id: '/menulis-hijaiyah',
  path: '/menulis-hijaiyah',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraIndexRoute = IqraIndexRouteImport.update({
  id: '/iqra/',
  path: '/iqra/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyatPendekIndexRoute = AyatPendekIndexRouteImport.update({
  id: '/ayat-pendek/',
  path: '/ayat-pendek/',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraTanwinRoute = IqraTanwinRouteImport.update({
  id: '/iqra/tanwin',
  path: '/iqra/tanwin',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraSukunTasydidRoute = IqraSukunTasydidRouteImport.update({
  id: '/iqra/sukun-tasydid',
  path: '/iqra/sukun-tasydid',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraSambungHurufRoute = IqraSambungHurufRouteImport.update({
  id: '/iqra/sambung-huruf',
  path: '/iqra/sambung-huruf',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraMadRoute = IqraMadRouteImport.update({
  id: '/iqra/mad',
  path: '/iqra/mad',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraHarakatRoute = IqraHarakatRouteImport.update({
  id: '/iqra/harakat',
  path: '/iqra/harakat',
  getParentRoute: () => rootRouteImport,
} as any)
const AyatPendekSurahRoute = AyatPendekSurahRouteImport.update({
  id: '/ayat-pendek/$surah',
  path: '/ayat-pendek/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraHijaiyahIndexRoute = IqraHijaiyahIndexRouteImport.update({
  id: '/iqra/hijaiyah/',
  path: '/iqra/hijaiyah/',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraHijaiyahLetterRoute = IqraHijaiyahLetterRouteImport.update({
  id: '/iqra/hijaiyah/$letter',
  path: '/iqra/hijaiyah/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const AyatPendekIsyaratSurahRoute = AyatPendekIsyaratSurahRouteImport.update({
  id: '/ayat-pendek/isyarat/$surah',
  path: '/ayat-pendek/isyarat/$surah',
  getParentRoute: () => rootRouteImport,
} as any)
const IqraHijaiyahIsyaratLetterRoute =
  IqraHijaiyahIsyaratLetterRouteImport.update({
    id: '/iqra/hijaiyah/isyarat/$letter',
    path: '/iqra/hijaiyah/isyarat/$letter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menulis-hijaiyah': typeof MenulisHijaiyahRoute
  '/siswa': typeof SiswaRoute
  '/ayat-pendek/$surah': typeof AyatPendekSurahRoute
  '/iqra/harakat': typeof IqraHarakatRoute
  '/iqra/mad': typeof IqraMadRoute
  '/iqra/sambung-huruf': typeof IqraSambungHurufRoute
  '/iqra/sukun-tasydid': typeof IqraSukunTasydidRoute
  '/iqra/tanwin': typeof IqraTanwinRoute
  '/ayat-pendek/': typeof AyatPendekIndexRoute
  '/iqra/': typeof IqraIndexRoute
  '/ayat-pendek/isyarat/$surah': typeof AyatPendekIsyaratSurahRoute
  '/iqra/hijaiyah/$letter': typeof IqraHijaiyahLetterRoute
  '/iqra/hijaiyah/': typeof IqraHijaiyahIndexRoute
  '/iqra/hijaiyah/isyarat/$letter': typeof IqraHijaiyahIsyaratLetterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menulis-hijaiyah': typeof MenulisHijaiyahRoute
  '/siswa': typeof SiswaRoute
  '/ayat-pendek/$surah': typeof AyatPendekSurahRoute
  '/iqra/harakat': typeof IqraHarakatRoute
  '/iqra/mad': typeof IqraMadRoute
  '/iqra/sambung-huruf': typeof IqraSambungHurufRoute
  '/iqra/sukun-tasydid': typeof IqraSukunTasydidRoute
  '/iqra/tanwin': typeof IqraTanwinRoute
  '/ayat-pendek': typeof AyatPendekIndexRoute
  '/iqra': typeof IqraIndexRoute
  '/ayat-pendek/isyarat/$surah': typeof AyatPendekIsyaratSurahRoute
  '/iqra/hijaiyah/$letter': typeof IqraHijaiyahLetterRoute
  '/iqra/hijaiyah': typeof IqraHijaiyahIndexRoute
  '/iqra/hijaiyah/isyarat/$letter': typeof IqraHijaiyahIsyaratLetterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/menulis-hijaiyah': typeof MenulisHijaiyahRoute
  '/siswa': typeof SiswaRoute
  '/ayat-pendek/$surah': typeof AyatPendekSurahRoute
  '/iqra/harakat': typeof IqraHarakatRoute
  '/iqra/mad': typeof IqraMadRoute
  '/iqra/sambung-huruf': typeof IqraSambungHurufRoute
  '/iqra/sukun-tasydid': typeof IqraSukunTasydidRoute
  '/iqra/tanwin': typeof IqraTanwinRoute
  '/ayat-pendek/': typeof AyatPendekIndexRoute
  '/iqra/': typeof IqraIndexRoute
  '/ayat-pendek/isyarat/$surah': typeof AyatPendekIsyaratSurahRoute
  '/iqra/hijaiyah/$letter': typeof IqraHijaiyahLetterRoute
  '/iqra/hijaiyah/': typeof IqraHijaiyahIndexRoute
  '/iqra/hijaiyah/isyarat/$letter': typeof IqraHijaiyahIsyaratLetterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menulis-hijaiyah'
    | '/siswa'
    | '/ayat-pendek/$surah'
    | '/iqra/harakat'
    | '/iqra/mad'
    | '/iqra/sambung-huruf'
    | '/iqra/sukun-tasydid'
    | '/iqra/tanwin'
    | '/ayat-pendek/'
    | '/iqra/'
    | '/ayat-pendek/isyarat/$surah'
    | '/iqra/hijaiyah/$letter'
    | '/iqra/hijaiyah/'
    | '/iqra/hijaiyah/isyarat/$letter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menulis-hijaiyah'
    | '/siswa'
    | '/ayat-pendek/$surah'
    | '/iqra/harakat'
    | '/iqra/mad'
    | '/iqra/sambung-huruf'
    | '/iqra/sukun-tasydid'
    | '/iqra/tanwin'
    | '/ayat-pendek'
    | '/iqra'
    | '/ayat-pendek/isyarat/$surah'
    | '/iqra/hijaiyah/$letter'
    | '/iqra/hijaiyah'
    | '/iqra/hijaiyah/isyarat/$letter'
  id:
    | '__root__'
    | '/'
    | '/menulis-hijaiyah'
    | '/siswa'
    | '/ayat-pendek/$surah'
    | '/iqra/harakat'
    | '/iqra/mad'
    | '/iqra/sambung-huruf'
    | '/iqra/sukun-tasydid'
    | '/iqra/tanwin'
    | '/ayat-pendek/'
    | '/iqra/'
    | '/ayat-pendek/isyarat/$surah'
    | '/iqra/hijaiyah/$letter'
    | '/iqra/hijaiyah/'
    | '/iqra/hijaiyah/isyarat/$letter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MenulisHijaiyahRoute: typeof MenulisHijaiyahRoute
  SiswaRoute: typeof SiswaRoute
  AyatPendekSurahRoute: typeof AyatPendekSurahRoute
  IqraHarakatRoute: typeof IqraHarakatRoute
  IqraMadRoute: typeof IqraMadRoute
  IqraSambungHurufRoute: typeof IqraSambungHurufRoute
  IqraSukunTasydidRoute: typeof IqraSukunTasydidRoute
  IqraTanwinRoute: typeof IqraTanwinRoute
  AyatPendekIndexRoute: typeof AyatPendekIndexRoute
  IqraIndexRoute: typeof IqraIndexRoute
  AyatPendekIsyaratSurahRoute: typeof AyatPendekIsyaratSurahRoute
  IqraHijaiyahLetterRoute: typeof IqraHijaiyahLetterRoute
  IqraHijaiyahIndexRoute: typeof IqraHijaiyahIndexRoute
  IqraHijaiyahIsyaratLetterRoute: typeof IqraHijaiyahIsyaratLetterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menulis-hijaiyah': {
      id: '/menulis-hijaiyah'
      path: '/menulis-hijaiyah'
      fullPath: '/menulis-hijaiyah'
      preLoaderRoute: typeof MenulisHijaiyahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/': {
      id: '/iqra/'
      path: '/iqra'
      fullPath: '/iqra/'
      preLoaderRoute: typeof IqraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayat-pendek/': {
      id: '/ayat-pendek/'
      path: '/ayat-pendek'
      fullPath: '/ayat-pendek/'
      preLoaderRoute: typeof AyatPendekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/tanwin': {
      id: '/iqra/tanwin'
      path: '/iqra/tanwin'
      fullPath: '/iqra/tanwin'
      preLoaderRoute: typeof IqraTanwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/sukun-tasydid': {
      id: '/iqra/sukun-tasydid'
      path: '/iqra/sukun-tasydid'
      fullPath: '/iqra/sukun-tasydid'
      preLoaderRoute: typeof IqraSukunTasydidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/sambung-huruf': {
      id: '/iqra/sambung-huruf'
      path: '/iqra/sambung-huruf'
      fullPath: '/iqra/sambung-huruf'
      preLoaderRoute: typeof IqraSambungHurufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/mad': {
      id: '/iqra/mad'
      path: '/iqra/mad'
      fullPath: '/iqra/mad'
      preLoaderRoute: typeof IqraMadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/harakat': {
      id: '/iqra/harakat'
      path: '/iqra/harakat'
      fullPath: '/iqra/harakat'
      preLoaderRoute: typeof IqraHarakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayat-pendek/$surah': {
      id: '/ayat-pendek/$surah'
      path: '/ayat-pendek/$surah'
      fullPath: '/ayat-pendek/$surah'
      preLoaderRoute: typeof AyatPendekSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/hijaiyah/': {
      id: '/iqra/hijaiyah/'
      path: '/iqra/hijaiyah'
      fullPath: '/iqra/hijaiyah/'
      preLoaderRoute: typeof IqraHijaiyahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/hijaiyah/$letter': {
      id: '/iqra/hijaiyah/$letter'
      path: '/iqra/hijaiyah/$letter'
      fullPath: '/iqra/hijaiyah/$letter'
      preLoaderRoute: typeof IqraHijaiyahLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayat-pendek/isyarat/$surah': {
      id: '/ayat-pendek/isyarat/$surah'
      path: '/ayat-pendek/isyarat/$surah'
      fullPath: '/ayat-pendek/isyarat/$surah'
      preLoaderRoute: typeof AyatPendekIsyaratSurahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqra/hijaiyah/isyarat/$letter': {
      id: '/iqra/hijaiyah/isyarat/$letter'
      path: '/iqra/hijaiyah/isyarat/$letter'
      fullPath: '/iqra/hijaiyah/isyarat/$letter'
      preLoaderRoute: typeof IqraHijaiyahIsyaratLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenulisHijaiyahRoute: MenulisHijaiyahRoute,
  SiswaRoute: SiswaRoute,
  AyatPendekSurahRoute: AyatPendekSurahRoute,
  IqraHarakatRoute: IqraHarakatRoute,
  IqraMadRoute: IqraMadRoute,
  IqraSambungHurufRoute: IqraSambungHurufRoute,
  IqraSukunTasydidRoute: IqraSukunTasydidRoute,
  IqraTanwinRoute: IqraTanwinRoute,
  AyatPendekIndexRoute: AyatPendekIndexRoute,
  IqraIndexRoute: IqraIndexRoute,
  AyatPendekIsyaratSurahRoute: AyatPendekIsyaratSurahRoute,
  IqraHijaiyahLetterRoute: IqraHijaiyahLetterRoute,
  IqraHijaiyahIndexRoute: IqraHijaiyahIndexRoute,
  IqraHijaiyahIsyaratLetterRoute: IqraHijaiyahIsyaratLetterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
