/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherDashboardRouteImport } from './routes/_teacher-dashboard'
import { Route as StudentDashboardRouteImport } from './routes/_student-dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as TeacherDashboardGuruIndexRouteImport } from './routes/_teacher-dashboard/guru/index'
import { Route as StudentDashboardSiswaIndexRouteImport } from './routes/_student-dashboard/siswa/index'
import { Route as TeacherDashboardGuruMonitoringIndexRouteImport } from './routes/_teacher-dashboard/guru/monitoring/index'
import { Route as StudentDashboardSiswaMenulisHijaiyahIndexRouteImport } from './routes/_student-dashboard/siswa/menulis-hijaiyah/index'
import { Route as StudentDashboardSiswaIqraIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/index'
import { Route as StudentDashboardSiswaAyatPendekIndexRouteImport } from './routes/_student-dashboard/siswa/ayat-pendek/index'
import { Route as TeacherDashboardGuruMonitoringStudentIdIndexRouteImport } from './routes/_teacher-dashboard/guru/monitoring/$studentId/index'
import { Route as StudentDashboardSiswaIqraTanwinIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/tanwin/index'
import { Route as StudentDashboardSiswaIqraSukunTasydidIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/sukun-tasydid/index'
import { Route as StudentDashboardSiswaIqraSambungHurufIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/sambung-huruf/index'
import { Route as StudentDashboardSiswaIqraMadIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/mad/index'
import { Route as StudentDashboardSiswaIqraHijaiyahIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/hijaiyah/index'
import { Route as StudentDashboardSiswaIqraHarakatIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/harakat/index'
import { Route as StudentDashboardSiswaAyatPendekSurahIndexRouteImport } from './routes/_student-dashboard/siswa/ayat-pendek/$surah/index'
import { Route as StudentDashboardSiswaIqraHijaiyahLetterIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/hijaiyah/$letter/index'
import { Route as StudentDashboardSiswaAyatPendekSurahIsyaratIndexRouteImport } from './routes/_student-dashboard/siswa/ayat-pendek/$surah/isyarat/index'
import { Route as StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRouteImport } from './routes/_student-dashboard/siswa/iqra/hijaiyah/$letter/isyarat/index'

const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/_teacher-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/_student-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const TeacherDashboardGuruIndexRoute =
  TeacherDashboardGuruIndexRouteImport.update({
    id: '/guru/',
    path: '/guru/',
    getParentRoute: () => TeacherDashboardRoute,
  } as any)
const StudentDashboardSiswaIndexRoute =
  StudentDashboardSiswaIndexRouteImport.update({
    id: '/siswa/',
    path: '/siswa/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const TeacherDashboardGuruMonitoringIndexRoute =
  TeacherDashboardGuruMonitoringIndexRouteImport.update({
    id: '/guru/monitoring/',
    path: '/guru/monitoring/',
    getParentRoute: () => TeacherDashboardRoute,
  } as any)
const StudentDashboardSiswaMenulisHijaiyahIndexRoute =
  StudentDashboardSiswaMenulisHijaiyahIndexRouteImport.update({
    id: '/siswa/menulis-hijaiyah/',
    path: '/siswa/menulis-hijaiyah/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraIndexRoute =
  StudentDashboardSiswaIqraIndexRouteImport.update({
    id: '/siswa/iqra/',
    path: '/siswa/iqra/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaAyatPendekIndexRoute =
  StudentDashboardSiswaAyatPendekIndexRouteImport.update({
    id: '/siswa/ayat-pendek/',
    path: '/siswa/ayat-pendek/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const TeacherDashboardGuruMonitoringStudentIdIndexRoute =
  TeacherDashboardGuruMonitoringStudentIdIndexRouteImport.update({
    id: '/guru/monitoring/$studentId/',
    path: '/guru/monitoring/$studentId/',
    getParentRoute: () => TeacherDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraTanwinIndexRoute =
  StudentDashboardSiswaIqraTanwinIndexRouteImport.update({
    id: '/siswa/iqra/tanwin/',
    path: '/siswa/iqra/tanwin/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraSukunTasydidIndexRoute =
  StudentDashboardSiswaIqraSukunTasydidIndexRouteImport.update({
    id: '/siswa/iqra/sukun-tasydid/',
    path: '/siswa/iqra/sukun-tasydid/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraSambungHurufIndexRoute =
  StudentDashboardSiswaIqraSambungHurufIndexRouteImport.update({
    id: '/siswa/iqra/sambung-huruf/',
    path: '/siswa/iqra/sambung-huruf/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraMadIndexRoute =
  StudentDashboardSiswaIqraMadIndexRouteImport.update({
    id: '/siswa/iqra/mad/',
    path: '/siswa/iqra/mad/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraHijaiyahIndexRoute =
  StudentDashboardSiswaIqraHijaiyahIndexRouteImport.update({
    id: '/siswa/iqra/hijaiyah/',
    path: '/siswa/iqra/hijaiyah/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraHarakatIndexRoute =
  StudentDashboardSiswaIqraHarakatIndexRouteImport.update({
    id: '/siswa/iqra/harakat/',
    path: '/siswa/iqra/harakat/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaAyatPendekSurahIndexRoute =
  StudentDashboardSiswaAyatPendekSurahIndexRouteImport.update({
    id: '/siswa/ayat-pendek/$surah/',
    path: '/siswa/ayat-pendek/$surah/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraHijaiyahLetterIndexRoute =
  StudentDashboardSiswaIqraHijaiyahLetterIndexRouteImport.update({
    id: '/siswa/iqra/hijaiyah/$letter/',
    path: '/siswa/iqra/hijaiyah/$letter/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute =
  StudentDashboardSiswaAyatPendekSurahIsyaratIndexRouteImport.update({
    id: '/siswa/ayat-pendek/$surah/isyarat/',
    path: '/siswa/ayat-pendek/$surah/isyarat/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)
const StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute =
  StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRouteImport.update({
    id: '/siswa/iqra/hijaiyah/$letter/isyarat/',
    path: '/siswa/iqra/hijaiyah/$letter/isyarat/',
    getParentRoute: () => StudentDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/siswa/': typeof StudentDashboardSiswaIndexRoute
  '/guru/': typeof TeacherDashboardGuruIndexRoute
  '/siswa/ayat-pendek/': typeof StudentDashboardSiswaAyatPendekIndexRoute
  '/siswa/iqra/': typeof StudentDashboardSiswaIqraIndexRoute
  '/siswa/menulis-hijaiyah/': typeof StudentDashboardSiswaMenulisHijaiyahIndexRoute
  '/guru/monitoring/': typeof TeacherDashboardGuruMonitoringIndexRoute
  '/siswa/ayat-pendek/$surah/': typeof StudentDashboardSiswaAyatPendekSurahIndexRoute
  '/siswa/iqra/harakat/': typeof StudentDashboardSiswaIqraHarakatIndexRoute
  '/siswa/iqra/hijaiyah/': typeof StudentDashboardSiswaIqraHijaiyahIndexRoute
  '/siswa/iqra/mad/': typeof StudentDashboardSiswaIqraMadIndexRoute
  '/siswa/iqra/sambung-huruf/': typeof StudentDashboardSiswaIqraSambungHurufIndexRoute
  '/siswa/iqra/sukun-tasydid/': typeof StudentDashboardSiswaIqraSukunTasydidIndexRoute
  '/siswa/iqra/tanwin/': typeof StudentDashboardSiswaIqraTanwinIndexRoute
  '/guru/monitoring/$studentId/': typeof TeacherDashboardGuruMonitoringStudentIdIndexRoute
  '/siswa/ayat-pendek/$surah/isyarat/': typeof StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute
  '/siswa/iqra/hijaiyah/$letter/': typeof StudentDashboardSiswaIqraHijaiyahLetterIndexRoute
  '/siswa/iqra/hijaiyah/$letter/isyarat/': typeof StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/siswa': typeof StudentDashboardSiswaIndexRoute
  '/guru': typeof TeacherDashboardGuruIndexRoute
  '/siswa/ayat-pendek': typeof StudentDashboardSiswaAyatPendekIndexRoute
  '/siswa/iqra': typeof StudentDashboardSiswaIqraIndexRoute
  '/siswa/menulis-hijaiyah': typeof StudentDashboardSiswaMenulisHijaiyahIndexRoute
  '/guru/monitoring': typeof TeacherDashboardGuruMonitoringIndexRoute
  '/siswa/ayat-pendek/$surah': typeof StudentDashboardSiswaAyatPendekSurahIndexRoute
  '/siswa/iqra/harakat': typeof StudentDashboardSiswaIqraHarakatIndexRoute
  '/siswa/iqra/hijaiyah': typeof StudentDashboardSiswaIqraHijaiyahIndexRoute
  '/siswa/iqra/mad': typeof StudentDashboardSiswaIqraMadIndexRoute
  '/siswa/iqra/sambung-huruf': typeof StudentDashboardSiswaIqraSambungHurufIndexRoute
  '/siswa/iqra/sukun-tasydid': typeof StudentDashboardSiswaIqraSukunTasydidIndexRoute
  '/siswa/iqra/tanwin': typeof StudentDashboardSiswaIqraTanwinIndexRoute
  '/guru/monitoring/$studentId': typeof TeacherDashboardGuruMonitoringStudentIdIndexRoute
  '/siswa/ayat-pendek/$surah/isyarat': typeof StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute
  '/siswa/iqra/hijaiyah/$letter': typeof StudentDashboardSiswaIqraHijaiyahLetterIndexRoute
  '/siswa/iqra/hijaiyah/$letter/isyarat': typeof StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_student-dashboard': typeof StudentDashboardRouteWithChildren
  '/_teacher-dashboard': typeof TeacherDashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_student-dashboard/siswa/': typeof StudentDashboardSiswaIndexRoute
  '/_teacher-dashboard/guru/': typeof TeacherDashboardGuruIndexRoute
  '/_student-dashboard/siswa/ayat-pendek/': typeof StudentDashboardSiswaAyatPendekIndexRoute
  '/_student-dashboard/siswa/iqra/': typeof StudentDashboardSiswaIqraIndexRoute
  '/_student-dashboard/siswa/menulis-hijaiyah/': typeof StudentDashboardSiswaMenulisHijaiyahIndexRoute
  '/_teacher-dashboard/guru/monitoring/': typeof TeacherDashboardGuruMonitoringIndexRoute
  '/_student-dashboard/siswa/ayat-pendek/$surah/': typeof StudentDashboardSiswaAyatPendekSurahIndexRoute
  '/_student-dashboard/siswa/iqra/harakat/': typeof StudentDashboardSiswaIqraHarakatIndexRoute
  '/_student-dashboard/siswa/iqra/hijaiyah/': typeof StudentDashboardSiswaIqraHijaiyahIndexRoute
  '/_student-dashboard/siswa/iqra/mad/': typeof StudentDashboardSiswaIqraMadIndexRoute
  '/_student-dashboard/siswa/iqra/sambung-huruf/': typeof StudentDashboardSiswaIqraSambungHurufIndexRoute
  '/_student-dashboard/siswa/iqra/sukun-tasydid/': typeof StudentDashboardSiswaIqraSukunTasydidIndexRoute
  '/_student-dashboard/siswa/iqra/tanwin/': typeof StudentDashboardSiswaIqraTanwinIndexRoute
  '/_teacher-dashboard/guru/monitoring/$studentId/': typeof TeacherDashboardGuruMonitoringStudentIdIndexRoute
  '/_student-dashboard/siswa/ayat-pendek/$surah/isyarat/': typeof StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute
  '/_student-dashboard/siswa/iqra/hijaiyah/$letter/': typeof StudentDashboardSiswaIqraHijaiyahLetterIndexRoute
  '/_student-dashboard/siswa/iqra/hijaiyah/$letter/isyarat/': typeof StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/siswa/'
    | '/guru/'
    | '/siswa/ayat-pendek/'
    | '/siswa/iqra/'
    | '/siswa/menulis-hijaiyah/'
    | '/guru/monitoring/'
    | '/siswa/ayat-pendek/$surah/'
    | '/siswa/iqra/harakat/'
    | '/siswa/iqra/hijaiyah/'
    | '/siswa/iqra/mad/'
    | '/siswa/iqra/sambung-huruf/'
    | '/siswa/iqra/sukun-tasydid/'
    | '/siswa/iqra/tanwin/'
    | '/guru/monitoring/$studentId/'
    | '/siswa/ayat-pendek/$surah/isyarat/'
    | '/siswa/iqra/hijaiyah/$letter/'
    | '/siswa/iqra/hijaiyah/$letter/isyarat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/siswa'
    | '/guru'
    | '/siswa/ayat-pendek'
    | '/siswa/iqra'
    | '/siswa/menulis-hijaiyah'
    | '/guru/monitoring'
    | '/siswa/ayat-pendek/$surah'
    | '/siswa/iqra/harakat'
    | '/siswa/iqra/hijaiyah'
    | '/siswa/iqra/mad'
    | '/siswa/iqra/sambung-huruf'
    | '/siswa/iqra/sukun-tasydid'
    | '/siswa/iqra/tanwin'
    | '/guru/monitoring/$studentId'
    | '/siswa/ayat-pendek/$surah/isyarat'
    | '/siswa/iqra/hijaiyah/$letter'
    | '/siswa/iqra/hijaiyah/$letter/isyarat'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_student-dashboard'
    | '/_teacher-dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/_student-dashboard/siswa/'
    | '/_teacher-dashboard/guru/'
    | '/_student-dashboard/siswa/ayat-pendek/'
    | '/_student-dashboard/siswa/iqra/'
    | '/_student-dashboard/siswa/menulis-hijaiyah/'
    | '/_teacher-dashboard/guru/monitoring/'
    | '/_student-dashboard/siswa/ayat-pendek/$surah/'
    | '/_student-dashboard/siswa/iqra/harakat/'
    | '/_student-dashboard/siswa/iqra/hijaiyah/'
    | '/_student-dashboard/siswa/iqra/mad/'
    | '/_student-dashboard/siswa/iqra/sambung-huruf/'
    | '/_student-dashboard/siswa/iqra/sukun-tasydid/'
    | '/_student-dashboard/siswa/iqra/tanwin/'
    | '/_teacher-dashboard/guru/monitoring/$studentId/'
    | '/_student-dashboard/siswa/ayat-pendek/$surah/isyarat/'
    | '/_student-dashboard/siswa/iqra/hijaiyah/$letter/'
    | '/_student-dashboard/siswa/iqra/hijaiyah/$letter/isyarat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRouteWithChildren
  TeacherDashboardRoute: typeof TeacherDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_teacher-dashboard': {
      id: '/_teacher-dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student-dashboard': {
      id: '/_student-dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_teacher-dashboard/guru/': {
      id: '/_teacher-dashboard/guru/'
      path: '/guru'
      fullPath: '/guru/'
      preLoaderRoute: typeof TeacherDashboardGuruIndexRouteImport
      parentRoute: typeof TeacherDashboardRoute
    }
    '/_student-dashboard/siswa/': {
      id: '/_student-dashboard/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof StudentDashboardSiswaIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_teacher-dashboard/guru/monitoring/': {
      id: '/_teacher-dashboard/guru/monitoring/'
      path: '/guru/monitoring'
      fullPath: '/guru/monitoring/'
      preLoaderRoute: typeof TeacherDashboardGuruMonitoringIndexRouteImport
      parentRoute: typeof TeacherDashboardRoute
    }
    '/_student-dashboard/siswa/menulis-hijaiyah/': {
      id: '/_student-dashboard/siswa/menulis-hijaiyah/'
      path: '/siswa/menulis-hijaiyah'
      fullPath: '/siswa/menulis-hijaiyah/'
      preLoaderRoute: typeof StudentDashboardSiswaMenulisHijaiyahIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/': {
      id: '/_student-dashboard/siswa/iqra/'
      path: '/siswa/iqra'
      fullPath: '/siswa/iqra/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/ayat-pendek/': {
      id: '/_student-dashboard/siswa/ayat-pendek/'
      path: '/siswa/ayat-pendek'
      fullPath: '/siswa/ayat-pendek/'
      preLoaderRoute: typeof StudentDashboardSiswaAyatPendekIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_teacher-dashboard/guru/monitoring/$studentId/': {
      id: '/_teacher-dashboard/guru/monitoring/$studentId/'
      path: '/guru/monitoring/$studentId'
      fullPath: '/guru/monitoring/$studentId/'
      preLoaderRoute: typeof TeacherDashboardGuruMonitoringStudentIdIndexRouteImport
      parentRoute: typeof TeacherDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/tanwin/': {
      id: '/_student-dashboard/siswa/iqra/tanwin/'
      path: '/siswa/iqra/tanwin'
      fullPath: '/siswa/iqra/tanwin/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraTanwinIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/sukun-tasydid/': {
      id: '/_student-dashboard/siswa/iqra/sukun-tasydid/'
      path: '/siswa/iqra/sukun-tasydid'
      fullPath: '/siswa/iqra/sukun-tasydid/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraSukunTasydidIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/sambung-huruf/': {
      id: '/_student-dashboard/siswa/iqra/sambung-huruf/'
      path: '/siswa/iqra/sambung-huruf'
      fullPath: '/siswa/iqra/sambung-huruf/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraSambungHurufIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/mad/': {
      id: '/_student-dashboard/siswa/iqra/mad/'
      path: '/siswa/iqra/mad'
      fullPath: '/siswa/iqra/mad/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraMadIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/hijaiyah/': {
      id: '/_student-dashboard/siswa/iqra/hijaiyah/'
      path: '/siswa/iqra/hijaiyah'
      fullPath: '/siswa/iqra/hijaiyah/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraHijaiyahIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/harakat/': {
      id: '/_student-dashboard/siswa/iqra/harakat/'
      path: '/siswa/iqra/harakat'
      fullPath: '/siswa/iqra/harakat/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraHarakatIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/ayat-pendek/$surah/': {
      id: '/_student-dashboard/siswa/ayat-pendek/$surah/'
      path: '/siswa/ayat-pendek/$surah'
      fullPath: '/siswa/ayat-pendek/$surah/'
      preLoaderRoute: typeof StudentDashboardSiswaAyatPendekSurahIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/hijaiyah/$letter/': {
      id: '/_student-dashboard/siswa/iqra/hijaiyah/$letter/'
      path: '/siswa/iqra/hijaiyah/$letter'
      fullPath: '/siswa/iqra/hijaiyah/$letter/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraHijaiyahLetterIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/ayat-pendek/$surah/isyarat/': {
      id: '/_student-dashboard/siswa/ayat-pendek/$surah/isyarat/'
      path: '/siswa/ayat-pendek/$surah/isyarat'
      fullPath: '/siswa/ayat-pendek/$surah/isyarat/'
      preLoaderRoute: typeof StudentDashboardSiswaAyatPendekSurahIsyaratIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
    '/_student-dashboard/siswa/iqra/hijaiyah/$letter/isyarat/': {
      id: '/_student-dashboard/siswa/iqra/hijaiyah/$letter/isyarat/'
      path: '/siswa/iqra/hijaiyah/$letter/isyarat'
      fullPath: '/siswa/iqra/hijaiyah/$letter/isyarat/'
      preLoaderRoute: typeof StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRouteImport
      parentRoute: typeof StudentDashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface StudentDashboardRouteChildren {
  StudentDashboardSiswaIndexRoute: typeof StudentDashboardSiswaIndexRoute
  StudentDashboardSiswaAyatPendekIndexRoute: typeof StudentDashboardSiswaAyatPendekIndexRoute
  StudentDashboardSiswaIqraIndexRoute: typeof StudentDashboardSiswaIqraIndexRoute
  StudentDashboardSiswaMenulisHijaiyahIndexRoute: typeof StudentDashboardSiswaMenulisHijaiyahIndexRoute
  StudentDashboardSiswaAyatPendekSurahIndexRoute: typeof StudentDashboardSiswaAyatPendekSurahIndexRoute
  StudentDashboardSiswaIqraHarakatIndexRoute: typeof StudentDashboardSiswaIqraHarakatIndexRoute
  StudentDashboardSiswaIqraHijaiyahIndexRoute: typeof StudentDashboardSiswaIqraHijaiyahIndexRoute
  StudentDashboardSiswaIqraMadIndexRoute: typeof StudentDashboardSiswaIqraMadIndexRoute
  StudentDashboardSiswaIqraSambungHurufIndexRoute: typeof StudentDashboardSiswaIqraSambungHurufIndexRoute
  StudentDashboardSiswaIqraSukunTasydidIndexRoute: typeof StudentDashboardSiswaIqraSukunTasydidIndexRoute
  StudentDashboardSiswaIqraTanwinIndexRoute: typeof StudentDashboardSiswaIqraTanwinIndexRoute
  StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute: typeof StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute
  StudentDashboardSiswaIqraHijaiyahLetterIndexRoute: typeof StudentDashboardSiswaIqraHijaiyahLetterIndexRoute
  StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute: typeof StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute
}

const StudentDashboardRouteChildren: StudentDashboardRouteChildren = {
  StudentDashboardSiswaIndexRoute: StudentDashboardSiswaIndexRoute,
  StudentDashboardSiswaAyatPendekIndexRoute:
    StudentDashboardSiswaAyatPendekIndexRoute,
  StudentDashboardSiswaIqraIndexRoute: StudentDashboardSiswaIqraIndexRoute,
  StudentDashboardSiswaMenulisHijaiyahIndexRoute:
    StudentDashboardSiswaMenulisHijaiyahIndexRoute,
  StudentDashboardSiswaAyatPendekSurahIndexRoute:
    StudentDashboardSiswaAyatPendekSurahIndexRoute,
  StudentDashboardSiswaIqraHarakatIndexRoute:
    StudentDashboardSiswaIqraHarakatIndexRoute,
  StudentDashboardSiswaIqraHijaiyahIndexRoute:
    StudentDashboardSiswaIqraHijaiyahIndexRoute,
  StudentDashboardSiswaIqraMadIndexRoute:
    StudentDashboardSiswaIqraMadIndexRoute,
  StudentDashboardSiswaIqraSambungHurufIndexRoute:
    StudentDashboardSiswaIqraSambungHurufIndexRoute,
  StudentDashboardSiswaIqraSukunTasydidIndexRoute:
    StudentDashboardSiswaIqraSukunTasydidIndexRoute,
  StudentDashboardSiswaIqraTanwinIndexRoute:
    StudentDashboardSiswaIqraTanwinIndexRoute,
  StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute:
    StudentDashboardSiswaAyatPendekSurahIsyaratIndexRoute,
  StudentDashboardSiswaIqraHijaiyahLetterIndexRoute:
    StudentDashboardSiswaIqraHijaiyahLetterIndexRoute,
  StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute:
    StudentDashboardSiswaIqraHijaiyahLetterIsyaratIndexRoute,
}

const StudentDashboardRouteWithChildren =
  StudentDashboardRoute._addFileChildren(StudentDashboardRouteChildren)

interface TeacherDashboardRouteChildren {
  TeacherDashboardGuruIndexRoute: typeof TeacherDashboardGuruIndexRoute
  TeacherDashboardGuruMonitoringIndexRoute: typeof TeacherDashboardGuruMonitoringIndexRoute
  TeacherDashboardGuruMonitoringStudentIdIndexRoute: typeof TeacherDashboardGuruMonitoringStudentIdIndexRoute
}

const TeacherDashboardRouteChildren: TeacherDashboardRouteChildren = {
  TeacherDashboardGuruIndexRoute: TeacherDashboardGuruIndexRoute,
  TeacherDashboardGuruMonitoringIndexRoute:
    TeacherDashboardGuruMonitoringIndexRoute,
  TeacherDashboardGuruMonitoringStudentIdIndexRoute:
    TeacherDashboardGuruMonitoringStudentIdIndexRoute,
}

const TeacherDashboardRouteWithChildren =
  TeacherDashboardRoute._addFileChildren(TeacherDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRouteWithChildren,
  TeacherDashboardRoute: TeacherDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
